M&A: Tag when a company discusses the merger or acquisition/investment of
    another business, asset, stake, or entity. Either completed, planned, or under
    negotiation with the intent to expand capabilities, footprint, or offerings. Exclude
    internal investments, divestitures, or non-equity partnerships

Product expansion: Tag when a company discussses about new business growth, product mix,
    depth of coverage, product innovation, product portfolio expansion etc

Macro factors: Tag if Discussions includes general macroeconomic weakness or uncertainty
    (e.g., recessionary fears, volatility, slowdown, soft environment, slow activity,
    inflation, interest rate, catastrophe events, surrenders or change in policyholder
    behavior etc)

Strategy: Tag when a company discussses growth strategy, distribution channel
    optimisation, market expansion including geographic diversification or segment
    expansion

Operational/ cost efficiency: Tag if discussion includes operational or cost efficiency in insurance
    to minimize administrative and claims processing costs. Also highlight in case
    the discussion mentions rise in such costs

Business/ top line growth: Tag if discussion talks about increase in top line growth, customer
    retention, cross selling, pricing strategy, risk based pricing etc.

Workforce: Tag if discussion includes details around workforce reduction, organisational
    redesign, strategic workforce planning or operating model assessment etc.

Regulatory or accounting update: Tag if discussion includes impact of regulatory or legislative changes,
    IFRS17 or GAAP updates and any details around tax changes/implications

Launch of wellness apps and AI chatbots: Tag when a company is focused on building in-house tech and digital
    capabilities  including wellness platforms and AI chatbots for customers as well
    as distribution partners

